ALL:
  - "indices:*"
MANAGE:
  - "indices:monitor/*"
  - "indices:admin/*"
CREATE_INDEX:
  - "indices:admin/create"
  - "indices:admin/mapping/put"
MANAGE_ALIASES:
  - "indices:admin/aliases*"
MONITOR:
  - "indices:monitor/*"
DATA_ACCESS:
  - "indices:data/*"
  - "indices:admin/mapping/put"
WRITE:
  - "indices:data/write*"
  - "indices:admin/mapping/put"
READ:
  - "indices:data/read*"
DELETE:
  - "indices:data/write/delete*"
CRUD:
  - READ
  - WRITE
SEARCH:
  - "indices:data/read/search*"
  - "indices:data/read/msearch*"
  - SUGGEST
SUGGEST:
  - "indices:data/read/suggest*"
INDEX:
  - "indices:data/write/index*"
  - "indices:data/write/update*"
  - "indices:admin/mapping/put"
GET:
  - "indices:data/read/get*"
  - "indices:data/read/mget*"

KIBANA_INDEX_PATTERNS:
  - indices:data/read/get*
  - indices:data/read/mget*
  - indices:data/read/search*

KIBANA_INDEX_OTHER:
  - indices:admin/exists*
  - indices:admin/mapping/put*
  - indices:admin/mappings/fields/get*
  - indices:admin/refresh*
  - indices:admin/validate/query*
  - indices:data/read/get*
  - indices:data/read/mget*
  - indices:data/read/search*
  - indices:data/write/delete*
  - indices:data/write/index*
  - indices:data/write/update*

# CLUSTER
CLUSTER_ALL:
  - cluster:*
CLUSTER_MONITOR:
  - cluster:monitor/*
  
# HEALTH_AND_STATS = n"cluster:monitor/health*", "cluster:monitor/stats*", "indices:monitor/stats*", "cluster:monitor/nodes/stats*"
# ALL = cluster:*", "indices:admin/template/*